#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-bold
Version  : 1.3.0
Release  : 50
URL      : https://cran.r-project.org/src/contrib/bold_1.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bold_1.3.0.tar.gz
Summary  : Interface to Bold Systems API
Group    : Development/Tools
License  : MIT
Requires: R-crul
Requires: R-data.table
Requires: R-jsonlite
Requires: R-stringi
Requires: R-xml2
BuildRequires : R-crul
BuildRequires : R-data.table
BuildRequires : R-jsonlite
BuildRequires : R-stringi
BuildRequires : R-vcr
BuildRequires : R-xml2
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
bold
====
[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](https://www.repostatus.org/badges/latest/active.svg)](https://www.repostatus.org/#active)
[![cran version](https://www.r-pkg.org/badges/version/bold)](https://cran.r-project.org/package=bold)
[![cran checks](https://badges.cranchecks.info/worst/bold.svg)](https://badges.cranchecks.info)
[![R-check](https://github.com/ropensci/bold/workflows/R-check/badge.svg)](https://github.com/ropensci/bold/actions/)
[![codecov.io](https://codecov.io/github/ropensci/bold/coverage.svg?branch=master)](https://app.codecov.io/gh/ropensci/bold?branch=master)
[![rstudio mirror downloads](https://cranlogs.r-pkg.org/badges/bold)](https://github.com/r-hub/cranlogs.app)

%prep
%setup -q -n bold

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683146663

%install
export SOURCE_DATE_EPOCH=1683146663
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bold/DESCRIPTION
/usr/lib64/R/library/bold/INDEX
/usr/lib64/R/library/bold/LICENSE
/usr/lib64/R/library/bold/Meta/Rd.rds
/usr/lib64/R/library/bold/Meta/data.rds
/usr/lib64/R/library/bold/Meta/features.rds
/usr/lib64/R/library/bold/Meta/hsearch.rds
/usr/lib64/R/library/bold/Meta/links.rds
/usr/lib64/R/library/bold/Meta/nsInfo.rds
/usr/lib64/R/library/bold/Meta/package.rds
/usr/lib64/R/library/bold/NAMESPACE
/usr/lib64/R/library/bold/NEWS.md
/usr/lib64/R/library/bold/R/bold
/usr/lib64/R/library/bold/R/bold.rdb
/usr/lib64/R/library/bold/R/bold.rdx
/usr/lib64/R/library/bold/data/Rdata.rdb
/usr/lib64/R/library/bold/data/Rdata.rds
/usr/lib64/R/library/bold/data/Rdata.rdx
/usr/lib64/R/library/bold/help/AnIndex
/usr/lib64/R/library/bold/help/aliases.rds
/usr/lib64/R/library/bold/help/bold.rdb
/usr/lib64/R/library/bold/help/bold.rdx
/usr/lib64/R/library/bold/help/paths.rds
/usr/lib64/R/library/bold/html/00Index.html
/usr/lib64/R/library/bold/html/R.css
/usr/lib64/R/library/bold/tests/bold_trace_files/ids/ACRJP618-11[LepF1,LepR1]_F.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/ids/ACRJP619-11[LepF1,LepR1]_F.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/ids/ACRJP619-11[LepF1,LepR1]_R.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/ids/TRACE_FILE_INFO.txt
/usr/lib64/R/library/bold/tests/bold_trace_files/ids/bold_trace_files.tar
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO256-10[LepF1,LepR1]_F.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO256-10[LepF1,LepR1]_R.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO257-10[LepF1,LepR1]_F.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO257-10[LepF1,LepR1]_R.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO400-11[RonMWASPdeg_t1,LepR1]_F.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/BBBO400-11[RonMWASPdeg_t1,LepR1]_R.ab1
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/TRACE_FILE_INFO.txt
/usr/lib64/R/library/bold/tests/bold_trace_files/taxon/bold_trace_files.tar
/usr/lib64/R/library/bold/tests/fixtures/bold_identify.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_identify_parents.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_identify_taxonomy.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_seq.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_seqspec.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_specimens.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_stats.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_tax_id2.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_tax_name.yml
/usr/lib64/R/library/bold/tests/fixtures/bold_trace.yml
/usr/lib64/R/library/bold/tests/test-all.R
/usr/lib64/R/library/bold/tests/testthat/bold_identify_list.rda
/usr/lib64/R/library/bold/tests/testthat/helper-bold.R
/usr/lib64/R/library/bold/tests/testthat/setup_cassettes.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_filter.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_get_attr.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_identify.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_identify_parents.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_identify_taxonomy.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_seq.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_seqspec.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_specimens.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_stats.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_tax_id.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_tax_id2.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_tax_name.R
/usr/lib64/R/library/bold/tests/testthat/test-bold_trace.R
