#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bold
Version  : 0.5.0
Release  : 3
URL      : https://cran.r-project.org/src/contrib/bold_0.5.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bold_0.5.0.tar.gz
Summary  : Interface to Bold Systems API
Group    : Development/Tools
License  : MIT
Requires: R-crul
Requires: R-data.table
Requires: R-plyr
Requires: R-reshape
Requires: R-tibble
Requires: R-xml2
BuildRequires : R-crul
BuildRequires : R-data.table
BuildRequires : R-plyr
BuildRequires : R-reshape
BuildRequires : R-tibble
BuildRequires : R-xml2
BuildRequires : clr-R-helpers

%description
bold
====
[![Project Status: Active â The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)
![](https://img.shields.io/badge/CRAN/GitHub-0.4.0_/0.4.4.9120-blue.svg)

%prep
%setup -q -c -n bold

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530308858

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1530308858
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bold
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bold
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bold
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library bold|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bold/DESCRIPTION
/usr/lib64/R/library/bold/INDEX
/usr/lib64/R/library/bold/LICENSE
/usr/lib64/R/library/bold/Meta/Rd.rds
/usr/lib64/R/library/bold/Meta/data.rds
/usr/lib64/R/library/bold/Meta/features.rds
/usr/lib64/R/library/bold/Meta/hsearch.rds
/usr/lib64/R/library/bold/Meta/links.rds
/usr/lib64/R/library/bold/Meta/nsInfo.rds
/usr/lib64/R/library/bold/Meta/package.rds
/usr/lib64/R/library/bold/Meta/vignette.rds
/usr/lib64/R/library/bold/NAMESPACE
/usr/lib64/R/library/bold/NEWS.md
/usr/lib64/R/library/bold/R/bold
/usr/lib64/R/library/bold/R/bold.rdb
/usr/lib64/R/library/bold/R/bold.rdx
/usr/lib64/R/library/bold/data/Rdata.rdb
/usr/lib64/R/library/bold/data/Rdata.rds
/usr/lib64/R/library/bold/data/Rdata.rdx
/usr/lib64/R/library/bold/doc/bold_vignette.Rmd
/usr/lib64/R/library/bold/doc/bold_vignette.html
/usr/lib64/R/library/bold/doc/index.html
/usr/lib64/R/library/bold/help/AnIndex
/usr/lib64/R/library/bold/help/aliases.rds
/usr/lib64/R/library/bold/help/bold.rdb
/usr/lib64/R/library/bold/help/bold.rdx
/usr/lib64/R/library/bold/help/paths.rds
/usr/lib64/R/library/bold/html/00Index.html
/usr/lib64/R/library/bold/html/R.css
